/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Community;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author arjun
 */
public class CommunityAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    UserAccount userAccount;
   

    public CommunityAdminWorkAreaJPanel(JPanel userProcessContainer , UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        

        enterpriseNameLabel.setText(enterprise.getName()); //erated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

//    public CommunityAdminWorkAreaJPanel(JPanel UserContainer, UserAccount userAccount, ClinicOrganization clinicOrganization, Enterprise enterprise, EcoSystem system) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseNameLabel = new javax.swing.JTextField();
        btnRequestServiceProvider = new javax.swing.JButton();
        btnRequestHospital = new javax.swing.JButton();
        btnDonateBlood = new javax.swing.JButton();

        enterpriseNameLabel.setText("jTextField1");

        btnRequestServiceProvider.setText("Request Other Services");
        btnRequestServiceProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestServiceProviderActionPerformed(evt);
            }
        });

        btnRequestHospital.setText("Request Health Aid");
        btnRequestHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHospitalActionPerformed(evt);
            }
        });

        btnDonateBlood.setText("Donate Blood");
        btnDonateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateBloodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(btnRequestServiceProvider)
                .addGap(53, 53, 53)
                .addComponent(enterpriseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnRequestHospital))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnDonateBlood)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(enterpriseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnRequestServiceProvider)))
                .addGap(31, 31, 31)
                .addComponent(btnRequestHospital)
                .addGap(34, 34, 34)
                .addComponent(btnDonateBlood)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestServiceProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestServiceProviderActionPerformed
        // TODO add your handling code here:
        RequestServiceProviderJPanel requestServiceProviderJPanel = new RequestServiceProviderJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestServiceProviderJPanel",requestServiceProviderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRequestServiceProviderActionPerformed

    private void btnRequestHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHospitalActionPerformed
        // TODO add your handling code here:
        RequestHospitalJPanel requestHospitalJPanel = new RequestHospitalJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestHospitalJPanel",requestHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestHospitalActionPerformed

    private void btnDonateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateBloodActionPerformed
        // TODO add your handling code here:
        RequestDonateBloodJPanel requestDonateBloodJPanel = new RequestDonateBloodJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestDonateBloodJPanel",requestDonateBloodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnDonateBloodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonateBlood;
    private javax.swing.JButton btnRequestHospital;
    private javax.swing.JButton btnRequestServiceProvider;
    private javax.swing.JTextField enterpriseNameLabel;
    // End of variables declaration//GEN-END:variables
}
