/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Community;

import Business.FoodAndShelterDistributor.Food;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.WorkQueue.CommunityFoodRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arjun
 */
public class RequestServiceProviderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestServiceProviderJPanel
     * 
     */
     private JPanel userProcessContainer;
//    private ClinicOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem ecoSystem;
//    public RequestServiceProviderJPanel() {
//        initComponents();
//        
//    }

    public RequestServiceProviderJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.ecoSystem = ecoSystem;
        tblRequest.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateFoodTypeComboBox();
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtPurpose = new javax.swing.JTextField();
        btnSendRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        foodTypeComboBox = new javax.swing.JComboBox<>();
        txtVenue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeopleCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        jLabel1.setText("Request For Food Assistance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 360, -1));

        btnBack.setBackground(new java.awt.Color(102, 217, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        txtPurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurposeActionPerformed(evt);
            }
        });
        add(txtPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 129, -1));

        btnSendRequest.setBackground(new java.awt.Color(102, 217, 255));
        btnSendRequest.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        add(btnSendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        tblRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRequest.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Type", "Number of People Affected", "Venue", "Requested Date", "Resolution Date", "Number of Packets", "Status", "Sender", "Receiver"
            }
        ));
        tblRequest.setGridColor(new java.awt.Color(0, 0, 0));
        tblRequest.setShowGrid(true);
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 860, 176));

        jLabel7.setText("#People req:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        foodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(foodTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 138, -1));
        add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 129, -1));

        jLabel2.setText("Food Type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));
        add(txtPeopleCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 129, -1));

        jLabel5.setText("Location:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel3.setText("#Food Packets: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IndividualOpaque.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 795, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurposeActionPerformed

    
     private void populateFoodTypeComboBox(){
        DefaultComboBoxModel modelDoctorType = new DefaultComboBoxModel();
        for (Food food : ecoSystem.getFoodDirectory().getFoodList() ) {
            modelDoctorType.addElement(food.getFoodType());
        }
        
        foodTypeComboBox.setModel(modelDoctorType);
    }
    
    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        
        if(txtPeopleCount.getText().isEmpty() || txtPurpose.getText().isEmpty() || txtVenue.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please add all the fields");
        return;
        }
        
        CommunityFoodRequest request =  new CommunityFoodRequest();
        Date date = new Date();
        request.setRequestDate(date);
        request.setLocation(txtVenue.getText());
        
        try{
                request.setNoPeopleRequestingFood(Integer.parseInt(txtPeopleCount.getText()));
                request.setNoOfPackets(Integer.parseInt(txtPurpose.getText()));

        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Please enter numeric values");
        return;
        }
        
        request.setStatus("Requested");
        request.setSender(account);
        
        try{
            request.setRequestedFoodType(foodTypeComboBox.getSelectedItem().toString());

        }catch(NullPointerException n){
         JOptionPane.showMessageDialog(this, "Please wait for an update");
        return;
        }
        
        account.getWorkQueue().getWorkRequestList().add(request);
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        ecoSystem.getWorkQueue().getWorkRequestList().add(request);
        populateRequestTable();
    }//GEN-LAST:event_btnSendRequestActionPerformed

    
    private void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        for(WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
            if(work instanceof CommunityFoodRequest && work.getSender() == account){
                Object[] row = new Object[9];
                row[0] = ((CommunityFoodRequest) work).getRequestedFoodType() ;
                row[3] = ((CommunityFoodRequest) work).getRequestDate() ;
                row[1] = ((CommunityFoodRequest) work).getNoPeopleRequestingFood() ;
                row[2] = ((CommunityFoodRequest) work).getLocation() ;
                row[6] = work;
                row[5] = ((CommunityFoodRequest) work).getNoOfPackets() ;
                row[4] = ((CommunityFoodRequest) work).getResolveDate();
                row[7] = ((CommunityFoodRequest) work).getSender().getUsername();
                
                if(((CommunityFoodRequest) work).getReceiver() != null){
                row[8] = ((CommunityFoodRequest) work).getReceiver().getUsername();
                }
                
                
                model.addRow(row);
            
            }
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> foodTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtPeopleCount;
    private javax.swing.JTextField txtPurpose;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
