/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Community;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.WorkQueue.PatientDoctorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meghanshubhatt
 */
public class RequestDoctorCommunityAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDoctorCommunityAreaJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    EcoSystem ecoSystem;


    public RequestDoctorCommunityAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        tblRequestTablePatient.getTableHeader().setDefaultRenderer(new HeaderColors());
        
        fillTheRequestTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestTablePatient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientAge = new javax.swing.JTextField();
        txtPatientGender = new javax.swing.JTextField();
        txtPurposeVisit = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequestTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Gender", "Purpose of Visit", "Request Date", "Resolve Date", "Doctor Name", "Status", "Sender", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequestTablePatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 695, 245));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Patient Request Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 6, 290, 37));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Patient Name: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 226, -1, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Patient Age: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Patient Gender: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 356, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Purpose of Visit: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 124, -1));
        add(txtPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 124, -1));
        add(txtPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 124, -1));

        txtPurposeVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurposeVisitActionPerformed(evt);
            }
        });
        add(txtPurposeVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 124, -1));

        btnCreate.setBackground(new java.awt.Color(102, 217, 255));
        btnCreate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCreate.setText("Create Request");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 217, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emergencyServiceManager700x.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 1020, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPurposeVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurposeVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurposeVisitActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtPatientAge.getText().isEmpty() || txtPatientGender.getText().isEmpty() || txtPatientName.getText().isEmpty() || txtPurposeVisit.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Please add all the fields");
        return;
        
        
        }
        
        PatientDoctorRequest request = new PatientDoctorRequest();
        request.setPatientName(txtPatientName.getText());
        
        try{
                request.setPatientAge(Integer.parseInt(txtPatientAge.getText()));

        }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(this, "Please enter numeric value for age field");
        return;
        }
        
        request.setPatientGender(txtPatientGender.getText());
        request.setPurposeOfVisit(txtPurposeVisit.getText());
        
        Date requestDate = new Date();
        request.setRequestDate(requestDate); 
        
        request.setStatus("Requested");
        request.setSender(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        ecoSystem.getWorkQueue().getWorkRequestList().add(request);
        
        
        
        fillTheRequestTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequestTablePatient;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientGender;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPurposeVisit;
    // End of variables declaration//GEN-END:variables

    private void fillTheRequestTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblRequestTablePatient.getModel();
        
        model.setRowCount(0);
        

        for (WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
           if(work instanceof PatientDoctorRequest && work.getSender() == userAccount){ 
            Object[] row = new Object[10];
            row[0] = ((PatientDoctorRequest) work).getPatientName();
            row[1] = ((PatientDoctorRequest) work).getPatientAge();
            row[2] = ((PatientDoctorRequest) work).getPatientGender();
            row[3] = ((PatientDoctorRequest) work).getPurposeOfVisit();
            row[4] = ((PatientDoctorRequest) work).getRequestDate();
            row[5] = ((PatientDoctorRequest) work).getResolveDate();
            row[6] = ((PatientDoctorRequest) work).getDoctorName();
            row[7] = work;
            row[8] = ((PatientDoctorRequest) work).getSender().getUsername();
            
            if(((PatientDoctorRequest) work).getReceiver() != null){
            row[9] = ((PatientDoctorRequest) work).getReceiver().getUsername();
            }
            
            
  
            model.addRow(row);
           }
        }
        
        
    }
}
