/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FoodAndShelter;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.WorkQueue.FoodOrgWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rk
 */

public class ManageFoodReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFoodReqJPanel
     */
    JPanel userProcessContainer;
   Enterprise enterprise;
   EcoSystem ecoSystem;
   UserAccount userAccount;
   OrganizationDirectory organizationDirectory;
   
   
    public ManageFoodReqJPanel(JPanel userProcessContainer,
   Enterprise enterprise,
   EcoSystem ecoSystem,
   UserAccount userAccount,
   OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organizationDirectory = organizationDirectory;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        jAvaFoodTable1.getTableHeader().setDefaultRenderer(new HeaderColors());
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jAvaFoodTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jAvaFoodTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Food Type", "Quantity", "Total Price", "Request Date", "Resolved Date", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jAvaFoodTable1);
        if (jAvaFoodTable1.getColumnModel().getColumnCount() > 0) {
            jAvaFoodTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE REQUESTS FROM FOOD ORGANIZATION");

        jButton1.setBackground(new java.awt.Color(102, 217, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Assign Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("Delete Request");

        jButton3.setBackground(new java.awt.Color(102, 217, 255));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("Approve Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton4.setText("Reject Request");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foo.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jButton1)
                            .addGap(36, 36, 36)
                            .addComponent(jButton2)
                            .addGap(44, 44, 44)
                            .addComponent(jButton3)
                            .addGap(33, 33, 33)
                            .addComponent(jButton4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jAvaFoodTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to assign the Request", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            FoodOrgWorkRequest foodOrgWorkRequest = (FoodOrgWorkRequest) jAvaFoodTable1.getValueAt(selectedRow, 6);
            foodOrgWorkRequest.setStatus("Pending");
            foodOrgWorkRequest.setReceiver(userAccount);

            populateTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        
        int selectedRow = jAvaFoodTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to approve the Request", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            FoodOrgWorkRequest foodOrgWorkRequest = (FoodOrgWorkRequest) jAvaFoodTable1.getValueAt(selectedRow, 6);
            if(foodOrgWorkRequest.getStatus().equals("Pending")){
            foodOrgWorkRequest.setStatus("Approved");
            foodOrgWorkRequest.setReceiver(userAccount);
            foodOrgWorkRequest.setResolveDate(new Date());
            populateTable();
            }
            else{
              JOptionPane.showMessageDialog(null, "Request needs to be in Pending state to be Approved", "Warning", JOptionPane.WARNING_MESSAGE);
  
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

       public void populateTable(){
           
        DefaultTableModel table= (DefaultTableModel) jAvaFoodTable1.getModel();
        table.setRowCount(0);
        
         for(WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
            if(work instanceof FoodOrgWorkRequest){
                Object[] row = new Object[7];
             row[0] = ((FoodOrgWorkRequest) work).getFoodReqId();
            row[1] = ((FoodOrgWorkRequest) work).getFoodType();
            row[2] = ((FoodOrgWorkRequest) work).getQuantity() ;
            row[3] = ((FoodOrgWorkRequest) work).getTotalPrice();
            row[4] = work.getRequestDate();
            row[5] = work.getResolveDate();
            row[6] = work;
            table.addRow(row);
            }}
//            for (int i = 0; i < ecoSystem.getWorkQueue().getWorkRequestList().size(); i++) {
            
//            FoodOrgWorkRequest work = (FoodOrgWorkRequest) ecoSystem.getWorkQueue().getWorkRequestList().get(i);
            
           
          
//            }
            
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jAvaFoodTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
