/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ServiceProvider.Food;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodOrganization;
import Business.Organization.Organization;
import Business.RoundedBorder;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rk
 */
public class FoodAdminWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodAdminWAJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    FoodOrganization foodOrganization;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    public FoodAdminWAJPanel(JPanel userProcessContainer,
    UserAccount userAccount,
    FoodOrganization foodOrganization,
    Enterprise enterprise,
    EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.foodOrganization = foodOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        
        jMngInvBtn.setBorder(new RoundedBorder(20));
        jFoodReqBtn.setBorder(new RoundedBorder(20));
        jShelterReqBtn.setBorder(new RoundedBorder(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMngInvBtn = new javax.swing.JButton();
        jFoodReqBtn = new javax.swing.JButton();
        jShelterReqBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jMngInvBtn.setText("Manage Inventory");
        jMngInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMngInvBtnActionPerformed(evt);
            }
        });

        jFoodReqBtn.setText("Community Food Requests");
        jFoodReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodReqBtnActionPerformed(evt);
            }
        });

        jShelterReqBtn.setText("Community Shelter Requests");

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setText("FOOD ORGANIZATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jShelterReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFoodReqBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(199, 199, 199)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jMngInvBtn)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jMngInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jFoodReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jShelterReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFoodReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodReqBtnActionPerformed
        // TODO add your handling code here:
        ManageCommunityFoodRequestJPanel communityFoodRequestJPanel = new ManageCommunityFoodRequestJPanel(userProcessContainer,enterprise.getOrganizationDirectory(), enterprise, ecoSystem,userAccount);
        userProcessContainer.add("communityFoodRequestJPanel", communityFoodRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jFoodReqBtnActionPerformed

    private void jMngInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMngInvBtnActionPerformed
        // TODO add your handling code here:
         ManageFoodInventory manageFoodInventory = new ManageFoodInventory(userProcessContainer, enterprise, ecoSystem, userAccount,enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageFoodInventory", manageFoodInventory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jMngInvBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jFoodReqBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMngInvBtn;
    private javax.swing.JButton jShelterReqBtn;
    // End of variables declaration//GEN-END:variables
}
